version: "3.8"

services:

  # --------------------------
  # NGINX REVERSE PROXY
  # --------------------------
  nginx:
    build: ./nginx
    image: nginx:1.25-alpine
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  # --------------------------
  # DJANGO APPLICATION
  # --------------------------
  django_app:
    build:
      context: .
    image: django_app:latest
    container_name: django_cont
    env_file:
      - ".env"
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  # --------------------------
  # MYSQL DATABASE
  # --------------------------
  db:
    image: mysql:8.0
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

# --------------------------
# DOCKER NETWORK
# --------------------------
networks:
  notes-app-nw:
    driver: bridge