services:

  nginx:
    build: ./nginx
    image: custom_nginx:latest
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:latest
    container_name: django_cont
    env_file:
      - ".env"
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
      "
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - notes-app-nw

  db:
    image: mysql:8.0
    container_name: db_cont
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db  # Django DB_NAME
      MYSQL_USER: root         # <--- use root
      MYSQL_PASSWORD: root     # <--- use root
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
    driver: bridge