apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: note-app
spec:
  selector:
    app: notes-app   # <-- MUST match deployment labels
  ports:
    - port: 80
      targetPort: 8000
  type: NodePort