apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: note-app
spec:
  type: NodePort
  selector:
    app: notes-app   # MUST match deployment labels
  ports:
    - name: http
      port: 80          # service port
      targetPort: 8000  # containerPort in deployment
      nodePort: 30080   # exposed on your node (optional, or remove for auto-assign)